<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="MetricInputEdit.aspx.cs" Inherits="MetricTrac.MetricInputEdit"  MasterPageFile="~/MasterPage.master" %>
<%@ Register Namespace="MetricTrac.MTControls" TagPrefix="mt" Assembly="MetricTrac.Web"%>
<%@ Register src="../Control/MetricValueHistoryLog.ascx" tagname="MetricValueHistoryLog" tagprefix="uc" %>
<asp:Content ID="cntMetricValueInput" ContentPlaceHolderID="PageBody" runat="server">
<style type="text/css">
.riTextBox
{
    margin-left:0px;
    font-size:14pt;    
    padding:0px 0px 2px 2px;
    font-weight:bolder;    
    border:solid 1px Gray;
}
</style>
<div runat="server">
<script type="text/javascript" language="javascript">
    function GetRadWindow()
    {
         var oWindow = null;
         if (window.radWindow)
            oWindow = window.radWindow;     
         else if (window.frameElement.radWindow)
           oWindow = window.frameElement.radWindow;   
         return oWindow;
    }

    function ReloadWindowContent(w)
    {        
        w.BrowserWindow.location.href = w.BrowserWindow.location.href;
    }

    function CloseOnReload(IsCancel, arg) {        
        var w = GetRadWindow();
        if (!IsCancel) {
            ReloadWindowContent(w);
        }
        w.close(arg);        
    }

    var IsMetricInfoShown = true;

    function ShowHideMoreMetricInfo() {
        var w = GetRadWindow();
        var divMetricInfo = document.getElementById('divMetricInfo');
        var lnkShowHide = document.getElementById('lnkShowHide');        
        if (!IsMetricInfoShown) {            
            w.setSize(775, 525);            
            divMetricInfo.style.visibility = "visible";
            divMetricInfo.style.display = "block";
            lnkShowHide.innerHTML = '<img src="../images/Navigation/application_side_contract.png" alt="Hide More Info" style="border-style: none" />';
            lnkShowHide.title = "Hide More Info";
        }
        else {
            w.setSize(550, 525);
            divMetricInfo.style.visibility = "hidden";
            divMetricInfo.style.display = "none";
            lnkShowHide.innerHTML = '<img src="../images/Navigation/application_side_expand.png" alt="Show More Info" style="border-style: none" />';
            lnkShowHide.title = "Show More Info";
        }        
        IsMetricInfoShown = !IsMetricInfoShown;
    }    
</script>
</div>
    <table border="0" cellpadding="0" cellspacing="0"><tr><td valign="top" style="width:377px;">    
    <mt:MTDetailsView ObjectName="Metric Value" ID="mfMetricValue" runat="server" AutoGenerateInsertButton="True"
        AutoGenerateDeleteButton="False" AutoGenerateEditButton="True" DefaultMode="Edit"
        ShowCloseButtonSeparate="False" DataKeyNames="MetricValueID" AutoGenerateRows="false"
        RepeatColumns="1" DataSourceID="ldsMetricValue" 
        OnAction="mfMetricValue_Action"         
        OnItemUpdated="mfMetricValue_ItemUpdated" onprerender="mfMetricValue_PreRender" Width="377px" >
        <FooterStyle CssClass="Mf_F"></FooterStyle>
        <Fields>
            <mits:TemplateField HeaderText="Metric&nbsp;Category">                
                <ItemTemplate>                    
                    <asp:Label ID="lblMC" runat="server" CssClass="DefinedFields" Text='<%#Eval("MetricCategoryName") %>'>New</asp:Label>
                </ItemTemplate>
            </mits:TemplateField>
            <mits:TemplateField HeaderText="Org Location">
                <ItemTemplate>
                    <span class="DefinedFields"><%#Eval("OrgLocationFullName") %></span>
                </ItemTemplate>
            </mits:TemplateField>
            <mits:TemplateField HeaderText="Metric">            
                <ItemTemplate>                    
                    <asp:Label ID="lblMN" runat="server" Font-Size="11pt"  Font-Bold="true" CssClass="DefinedFields" Text='<%#Eval("MetricName") %>' />
                </ItemTemplate>
            </mits:TemplateField>            
            <mits:TemplateField HeaderText="Alias">
                <ItemTemplate>      
                    <asp:Label ID="lblAlias" runat="server" CssClass="DefinedFields" Text='<%#Eval("MetricOrgLocationAlias") %>' />
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox ID="tbAlias" runat="server" Text='<%#Eval("MetricOrgLocationAlias") %>' Columns="23" MaxLength="100"></asp:TextBox>
                </EditItemTemplate>
            </mits:TemplateField>
            <mits:TemplateField HeaderText="Code">
                <ItemTemplate>      
                    <asp:Label ID="lblCode" runat="server" CssClass="DefinedFields" Text='<%#Eval("MetricOrgLocationCode") %>' />
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox ID="tbCode" runat="server" Text='<%#Eval("MetricOrgLocationCode") %>' Columns="23" MaxLength="100"></asp:TextBox>
                </EditItemTemplate>
            </mits:TemplateField>            
            <mits:TemplateField HeaderText="Frequency">
                <ItemTemplate>                    
                    <asp:Label ID="lblFN" runat="server" CssClass="DefinedFields" Text='<%#Eval("MetricFrequencyName") %>' />
                </ItemTemplate>
            </mits:TemplateField>
            <mits:TemplateField HeaderText="Period">
                <ItemTemplate>                    
                    <asp:Label ID="lblP" CssClass="DefinedFields" Font-Size="11pt" runat="server" Text='<%#Eval("Period") %>' />
                </ItemTemplate>
            </mits:TemplateField>
            <mits:TemplateField HeaderText="Approval&nbsp;Status">
                <ItemTemplate>                    
                    <asp:Label ID="lblAppStatus" CssClass="DefinedFields" runat="server" Text='<%#Eval("ApprovalStatus") %>' />
                </ItemTemplate>    
                <EditItemTemplate>
                    <asp:DropDownList ID="ddlApprovalStatus" runat="server" Width="125px" SelectedValue='<%#Eval("Approved") %>'>
                        <asp:ListItem Value="False" Text="Pending" />
                        <asp:ListItem Value="" Text="Under Review" />
                        <asp:ListItem Value="True" Text="Approved" />
                    </asp:DropDownList> 
                </EditItemTemplate>            
            </mits:TemplateField>            
            <mits:TemplateField HeaderText="Value">
                <ItemTemplate>                    
                    <asp:Label ID="lblValueView" runat="server" CssClass="ViewValue" />&nbsp;&nbsp;<asp:Label ID="lblUoMView" runat="server" ForeColor="Black" />
                </ItemTemplate>
                <EditItemTemplate>
                    <div><asp:Label ID="lblOldValue" runat="server" /></div>
                    <table border="0" cellpadding="0" cellspacing="0"><tr><td>                    
                    <telerik:RadNumericTextBox ID="rntValue" runat="server" Type="Number" Culture="English (United States)"
                        Skin="" EnableEmbeddedSkins="false" Width="250px" /></td><td style="padding-top:1px;">
                    <asp:DropDownList ID="ddlInputUnitOfMeasure" runat="server" Width="100px"
                        DataSourceID="ldsInputUnitOfMeasure" DataTextField="SingularFullName" DataValueField="MeasureUnitId" AppendDataBoundItems="true" >
                        <asp:ListItem Text="" Value=""></asp:ListItem>
                    </asp:DropDownList>
                    </td></tr></table>
                    <asp:Label ID="lblUoM" runat="server" />
                    <div><asp:Label ID="lblRange" runat="server" Visible="false" /></div>
                    <asp:TextBox ID="tbValue" runat="server" Columns="38" MaxLength="500"  />                    
                    <asp:CheckBox ID="chbValue" runat="server" />                    
                    <telerik:RadDatePicker ID="rdpDateValue" runat="server" Culture="English (United States)" AllowEmpty="true" Width="150px" MinDate="02.01.1900 0:00:00" MaxDate="05.06.2079 0:00:00" Calendar-RangeMinDate="02.01.1900 0:00:00" Calendar-RangeMaxDate="05.06.2079 0:00:00" />
                </EditItemTemplate>                
            </mits:TemplateField>
            <mits:TemplateField HeaderText="Converted Value">
                <ItemTemplate>                    
                    <asp:Label ID="lblConvertedValue" runat="server" CssClass="ViewValue" />&nbsp;&nbsp;<asp:Label ID="lblOutputUoMView" runat="server" ForeColor="Black" />
                </ItemTemplate>
            </mits:TemplateField>                           
            <mits:TextBoxField HeaderText="Notes" DataField="Notes" Columns="46" 
                ConvertEmptyStringToNull="true" TextType="Text" TextMode="MultiLine" Rows="5" 
                ItemStyle-ForeColor="Black">            
                <ItemStyle ForeColor="Black"></ItemStyle>
            </mits:TextBoxField>
            <mits:TemplateField HeaderText="Comments to Data Collector">                
                <EditItemTemplate>
                    <asp:TextBox ID="tbComments" runat="server" MaxLength="500" Columns="46" 
                    ConvertEmptyStringToNull="true" TextType="Text" TextMode="MultiLine" Rows="5"   />
                </EditItemTemplate>                
                <ItemStyle ForeColor="Black"/>
            </mits:TemplateField>             
            <mits:TemplateField HeaderText="Files">
                <ItemTemplate>                    
                    <mfs:FileList ID="flFiles" runat="server" 
                        LocalObjectType="typeMetricValueFile" EnableDeleting="false" 
                        EnableDeletingConfirmation="false" EnableUploading="false"
                        RenderingMode="ThumbnailsList" ShowIcons="true" 
                        oninit="flFiles_Init" />
                </ItemTemplate>
                <EditItemTemplate>
                    <mfs:SimpleUpload ID="suFiles" runat="server" LocalObjectType="typeMetricValueFile"
                        MaxFilesCount="20" OverwriteExistingFiles="true" 
                        FocusOnLoad="false" EnablePopupWindow="false"
                        onload="suFiles_Load" ShowPaperclipImage="false" />
                </EditItemTemplate>
            </mits:TemplateField>
        </Fields>
        <EmptyDataRowStyle CssClass="Mf_R"></EmptyDataRowStyle>
        <EditRowStyle CssClass="Mf_R"></EditRowStyle>
        <HeaderStyle CssClass="Mf_H"></HeaderStyle>
        <AlternatingRowStyle CssClass="Mf_R"></AlternatingRowStyle>
        <RowStyle CssClass="Mf_R"></RowStyle>
    </mt:MTDetailsView>
    </td>
    <td style="width:10px;"></td>
    <td valign="top" style="padding-top:14px;">
        <asp:PlaceHolder ID="phHideBtn" runat="server">
        <a id="lnkShowHide" title="Hide More Info" href="javascript:ShowHideMoreMetricInfo();">
            <img src="../images/Navigation/application_side_contract.png" alt="Hide More Info" style="border-style: none" />
        </a></asp:PlaceHolder></td>
    <td style="width:10px;"></td>
    <td valign="top"  style="padding-top:14px;">
        <div id="divMetricInfo" style="visibility:visible; display:block;">
            <asp:PlaceHolder ID="phDescription" runat="server">
                <span class="GridHeader" style="color:#333333;">Description</span><br />
                <asp:Label ID="lblDescription" ForeColor="#999999" runat="server" />
            </asp:PlaceHolder>
            <hr id="hr1" runat="server" />
            <asp:PlaceHolder ID="phDefinition" runat="server">
                <span class="GridHeader" style="color:#333333;">Definition</span><br />
                <asp:Label ID="lblDefinition" ForeColor="#999999" runat="server" />
            </asp:PlaceHolder>
            <hr id="hr2" runat="server" />
            <asp:PlaceHolder ID="phDocumentation" runat="server">
                <span class="GridHeader" style="color:#333333;">Documentation</span><br />
                <asp:Label ID="lblDocumentation" ForeColor="#999999" runat="server" />
            </asp:PlaceHolder>
            <hr id="hr3" runat="server" />
            <asp:PlaceHolder ID="phReferences" runat="server">
                <span class="GridHeader" style="color:#333333;">References</span><br />
                <asp:Label ID="lblReferences" ForeColor="#999999" runat="server" />
            </asp:PlaceHolder>
        </div></td>
    </tr></table><br />
    <asp:Panel ID="pnlBtnClose" runat="server">
        <asp:Button ID="btnClose" runat="server" Text="Close" 
            style="padding: 7px 15px 7px 15px;" Width="150px" Font-Size="9pt" Font-Bold="true"
            OnClientClick="CloseOnReload(true, null); return false;" 
            onclick="btnClose_Click"  /><br /><br />
    </asp:Panel>
    <asp:Panel ID="pnlLog" runat="server">
        <uc:MetricValueHistoryLog ID="ValueHistoryLog" runat="server" />
    </asp:Panel>
    <asp:LinqDataSource runat="server" ID="ldsMetricValue" 
        ContextTypeName="MetricTrac.Bll.LinqMicajahDataContext" TableName="MetricValue"
        AutoGenerateWhereClause="true" 
        EnableInsert="false" EnableDelete="false" EnableUpdate="true" 
        onselecting="ldsMetricValue_Selecting" 
        onupdating="ldsMetricValue_Updating">
    </asp:LinqDataSource>
    <asp:LinqDataSource runat="server" ID="ldsInputUnitOfMeasure" 
    ContextTypeName="MetricTrac.Bll.LinqMicajahDataContext" 
        TableName="Mc_UnitsOfMeasure" onselecting="ldsInputUnitOfMeasure_Selecting"/>
</asp:Content>