<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="PerformanceIndicatorEdit.aspx.cs" Inherits="MetricTrac.PerformanceIndicatorEdit" MasterPageFile="~/MasterPage.master"%>
<%@ Register Src="~/Control/GCASelect.ascx" TagName="GCASelect" TagPrefix="c" %>
<%@ Register Src="~/Control/MetricList.ascx" TagName="MetricList" TagPrefix="c" %>
<%@ Register Namespace="MetricTrac.MTControls" TagPrefix="mt" Assembly="MetricTrac.Web"%>


<asp:Content ID="cntGCA" ContentPlaceHolderID="PageBody" runat="server">

    <div runat="server">
        <telerik:RadWindow runat="server" ID="rwEditValue" Modal="true" VisibleStatusbar="false" Height="525px" Width="790px" DestroyOnClose="false"
            OnClientClose="clientCloseMetricAdd"/>
        <script type="text/javascript">
            function OpenDialogWindow(url) {
                var oWnd = $find("<%=rwEditValue.ClientID%>");
                oWnd.argument = null;
                oWnd.setUrl(url);
                oWnd.Center();
                oWnd.show();
            }

            function clientCloseMetricAdd(sender, args) {
                if (sender.argument != "Save") return;
                var rapMetric = $find("<%=rapMetric.ClientID%>");
                rapMetric.ajaxRequest();
            }
        </script>
    </div>

    <mits:MagicForm ObjectName="Performance Indicator" ID="mfPerformanceIndicator"
        runat="server" AutoGenerateInsertButton="True"
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DefaultMode="Insert"
        ShowCloseButtonSeparate="False" DataKeyNames="PerformanceIndicatorID" AutoGenerateRows="false"
        RepeatColumns="1" DataSourceID="ldsPerformanceIndicator"
        OnAction="mfPerformanceIndicator_Action" 
        OnItemDeleted="mfPerformanceIndicator_ItemDeleted" 
        OnItemInserted="mfPerformanceIndicator_ItemInserted" 
        OnItemUpdated="mfPerformanceIndicator_ItemUpdated"
        OnDataBinding="mfPerformanceIndicator_DataBinding" 
        OnDataBound="mfPerformanceIndicator_DataBound" 
        oniteminserting="mfPerformanceIndicator_ItemInserting" 
        onitemupdating="mfPerformanceIndicator_ItemUpdating">
        <Fields>
            <mits:TextBoxField HeaderText="Name" DataField="Name" Columns="70" MaxLength="50" Required="true" />
            <mits:TextBoxField HeaderText="Alias" DataField="Alias" Columns="70" MaxLength="50" Required="false" />
            <mits:TextBoxField HeaderText="Code" DataField="Code" Columns="70" MaxLength="25" Required="false" />                                
            <mits:TemplateField>
                <EditItemTemplate>
                    <c:GCASelect runat="server" ID="sGroup" Width="380px" GCAID='<%#Bind("GroupCategoryAspectID")%>'/>
                </EditItemTemplate>
                <HeaderTemplate>GCA</HeaderTemplate>
            </mits:TemplateField>
            <mits:TemplateField>
                <EditItemTemplate>
                    <asp:DropDownList ID="ddlSector" runat="server" Width="380px"
                        DataSourceID="ldsSector" DataTextField="Name" DataValueField="SectorID" AppendDataBoundItems="true" SelectedValue='<%#Bind("SectorID") %>'>
                        <asp:ListItem Text="" Value=""></asp:ListItem>
                    </asp:DropDownList>
                </EditItemTemplate>
                <HeaderTemplate>Sector</HeaderTemplate>
            </mits:TemplateField>
            <mits:TemplateField>
                <EditItemTemplate>
                    <asp:DropDownList ID="ddlRequirement" runat="server" Width="380px"
                        DataSourceID="ldsRequirement" DataTextField="Name" DataValueField="RequirementID" AppendDataBoundItems="true" SelectedValue='<%#Bind("RequirementID") %>'>
                        <asp:ListItem Text="" Value=""></asp:ListItem>
                    </asp:DropDownList>
                </EditItemTemplate>
                <HeaderTemplate>Requirement</HeaderTemplate>
            </mits:TemplateField>                
            <mt:MTHtmlEditorField HeaderText="Description" DataField="Description" ToolsFile="~/includes/ToolsFiles/BasicTools.xml" ControlStyle-Height="210px" />            
            <mt:MTHtmlEditorField HeaderText="Help Text" DataField="Help" ToolsFile="~/includes/ToolsFiles/BasicTools.xml" ControlStyle-Height="210px" />
        </Fields>
    </mits:MagicForm>
    
    <br />
    <div runat="server">
        <telerik:RadAjaxPanel runat="server" ID="rapMetric" LoadingPanelID="lpMetric" EnableEmbeddedScripts="true" EnableAJAX="true">
            <table cellpadding="0" cellspacing="3">
                <tr>
                    <td><span class="Mf_Cpt">Metrics</span></td>
                    <td runat="server" align="right"><a class="Cgv_AddNew" href="javascript:OpenDialogWindow('MetricList.aspx?PerformanceIndicatorID=<%=PerformanceIndicatorID%>')">Add New Metric</a></td>
                </tr>
                <tr><td colspan="2">
                    <c:MetricList ID="cMetricList" runat="server" Mode="PIEdit" /></td></tr>
                <tr><td>&nbsp;</td></tr>
                <tr><td><span class="Mf_Cpt">Related Input Metrics</span></td></tr>
                <tr><td colspan="2">
                    <c:MetricList ID="RelatedMetric" runat="server" Mode="PiRef" />
                </td></tr>
            </table>
            <telerik:RadAjaxLoadingPanel runat="server" ID="lpMetric" Wrap="true" Transparency="33" BackColor="LightGray" ><table style="height:100%; width:100%">
                <tr><td valign="middle" align="center"><img alt="Loading ..." src="../images/loading6.gif" /></td></tr>
        </table></telerik:RadAjaxLoadingPanel>
        </telerik:RadAjaxPanel>
    </div>
     
    <bll:BllDataSource runat="server" ID="ldsMetric" TableName="Metric" BllSelectMethod="List" />
    
    <asp:LinqDataSource runat="server" ID="ldsPerformanceIndicator" ContextTypeName="MetricTrac.Bll.LinqMicajahDataContext" TableName="PerformanceIndicator"
        AutoGenerateWhereClause="true" EnableInsert="true" EnableDelete="true" EnableUpdate="true" OnInserting="ldsPerformanceIndicator_Inserting"/>
    <asp:LinqDataSource runat="server" ID="ldsSector" ContextTypeName="MetricTrac.Bll.LinqMicajahDataContext" TableName="Sector"/>
    <asp:LinqDataSource runat="server" ID="ldsRequirement" ContextTypeName="MetricTrac.Bll.LinqMicajahDataContext" TableName="Requirement"/>
</asp:Content>
