<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="PIFEdit.aspx.cs" Inherits="MetricTrac.PIFEdit" MasterPageFile="~/MasterPage.master"%>
<%@ Register src="~/Control/PerformanceIndicatorList.ascx" tagname="PerformanceIndicatorList" tagprefix="mts" %>
<asp:Content ID="cntPIFEdit" ContentPlaceHolderID="PageBody" runat="server">
    <mits:MagicForm ObjectName="Performance Indicator Form" ID="mfPerformanceIndicatorForm" runat="server" AutoGenerateInsertButton="True"
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DefaultMode="Insert"
        ShowCloseButtonSeparate="False" DataKeyNames="PerformanceIndicatorFormID" AutoGenerateRows="false"
        RepeatColumns="1" DataSourceID="ldsPerformanceIndicatorForm" 
        OnAction="mfPerformanceIndicatorForm_Action" OnItemDeleted="mfPerformanceIndicatorForm_ItemDeleted" OnItemInserted="mfPerformanceIndicatorForm_ItemInserted" OnItemUpdated="mfPerformanceIndicatorForm_ItemUpdated">
<FooterStyle CssClass="Mf_F"></FooterStyle>
        <Fields>
            <mits:TextBoxField HeaderText="Name" DataField="Name" Columns="55" Required="true" MaxLength="100"/>           
            <mits:TemplateField HeaderText="Performance<br>Indicators">
                <EditItemTemplate>
                    <mts:PerformanceIndicatorList ID="mainPerformanceIndicatorList" runat="server" ListMode="FormJunc" Width="700" />
                </EditItemTemplate>
            </mits:TemplateField>
            <mits:TemplateField>
                <EditItemTemplate> <br />
                    <asp:LinkButton ID="lbOrgTreeJunc" CssClass="SaveButtonCaption" runat="server" onclick="lbOrgTreeJunc_Click">Associate to Org Location</asp:LinkButton>
                </EditItemTemplate>
                <HeaderTemplate></HeaderTemplate>
            </mits:TemplateField>
        </Fields>

<EmptyDataRowStyle CssClass="Mf_R"></EmptyDataRowStyle>

<EditRowStyle CssClass="Mf_R"></EditRowStyle>

<HeaderStyle CssClass="Mf_H"></HeaderStyle>

<AlternatingRowStyle CssClass="Mf_R"></AlternatingRowStyle>

<RowStyle CssClass="Mf_R"></RowStyle>
    </mits:MagicForm>    
    <asp:LinqDataSource runat="server" ID="ldsPerformanceIndicatorForm" 
        ContextTypeName="MetricTrac.Bll.LinqMicajahDataContext" TableName="PerformanceIndicatorForm"
        AutoGenerateWhereClause="true" EnableInsert="true" EnableDelete="true" 
        EnableUpdate="true" 
        oninserted="ldsPerformanceIndicatorForm_Inserted" 
        onupdated="ldsPerformanceIndicatorForm_Updated" 
        onselected="ldsPerformanceIndicatorForm_Selected">
    </asp:LinqDataSource>
</asp:Content>
