<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="SaveFilter.aspx.cs" Inherits="MetricTrac.SaveFilter" MasterPageFile="~/MasterPage.master"%>
<%@ Register src="../Control/OrglocationMultipick.ascx" tagname="OrgLocationSelect" tagprefix="mts" %>
<%@ Register src="../Control/GCASelect.ascx" tagname="GCASelect" tagprefix="mts" %>
<asp:Content ID="cntFormJunc" ContentPlaceHolderID="PageBody" runat="server">
    <div id="Div1" runat="server">
        <script type="text/javascript">
            function GetRadWindow()
            {//123
                 var oWindow = null;
                 if (window.radWindow)
                    oWindow = window.radWindow;     
                 else if (window.frameElement.radWindow)
                   oWindow = window.frameElement.radWindow;   
                 return oWindow;
            }

            function CloseOnReload(IsCancel) {
                var w = GetRadWindow();
                if (IsCancel) w.argument = null;
                else w.argument = "Save";
                w.close();
            }
        </script>
        
        <mt:MTDetailsView runat="server" ObjectName="Metric Filter" ID="mfSaveFilter" DefaultMode="Insert"
            AutoGenerateInsertButton="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True"
            ShowCloseButtonSeparate="False" DataKeyNames="MetricFilterID" AutoGenerateRows="false" DataSourceID="dsMetricFilter" 
            OnAction="mfSaveFilter_Action" OnItemUpdated="mfSaveFilter_ItemUpdated" OnItemInserted="mfSaveFilter_ItemInserted" OnItemDeleted="mfSaveFilter_ItemDeleted"
            OnPreRender="mfSaveFilter_PreRender">
            <Fields>
                <mits:TextBoxField HeaderText="Name" DataField="Name" />
                <mits:TemplateField HeaderText="Org Location">
                    <ItemTemplate>                        
                        <mts:OrgLocationSelect ID="orgLocationSelect1" runat="server" Width="300px" AutoPostBack="true" />
                    </ItemTemplate>
                </mits:TemplateField>
                <mits:TemplateField HeaderText="Group Category Aspect">
                    <ItemTemplate>
                        <mts:GCASelect ID="cASelect" runat="server" Width="300px" GCAID='<%#Bind("GroupCategoryAspectID")%>' AutoPostBack="true" />
                    </ItemTemplate>
                </mits:TemplateField>
                <mt:MTDropDownListField DataField="PerformanceIndicatorFormID" HeaderText="PI Form" DataTextField="Name" DataValueField="PerformanceIndicatorFormID" DataSourceId="dsPIForm" AddEmptyItem="true" Width="300" AutoPostBack="true" />
                <mt:MTDropDownListField DataField="PerformanceIndicatorID" HeaderText="PI" DataTextField="Name" DataValueField="PerformanceIndicatorID" DataSourceId="dsPI" AddEmptyItem="true" Width="300" AutoPostBack="true" />
                <mt:MTDropDownListField DataField="MetricID" HeaderText="Metric" DataTextField="Name" DataValueField="MetricID" DataSourceId="dsMetric" Width="300" AddEmptyItem="true"/>
                <mt:MTDropDownListField DataField="DataCollectorID" HeaderText="Collector" DataTextField="FullName" DataValueField="UserID" DataSourceId="dsUser" AddEmptyItem="true" />
            </Fields>
        </mt:MTDetailsView>
    </div>
    
    <bll:BllDataSource runat="server" ID="dsMetricFilter" TableName="MetricFilter" 
        BllSelectMethod="List" EnableAllChange="True" 
        oninserting="dsMetricFilter_Inserting1"/>
    
    <bll:BllDataSource runat="server" ID="dsUser" TableName="Mc_User" BllSelectMethod="List"/>
    <bll:BllDataSource runat="server" ID="dsPIForm" TableName="PerformanceIndicatorForm" OrderBy="Name"/>
    <bll:BllDataSource runat="server" ID="dsPI" TableName="PerformanceIndicator" OrderBy="Name"/>
    <bll:BllDataSource runat="server" ID="dsMetric" TableName="Metric" OrderBy="Name"/>
</asp:Content>