<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="SaveFilter.aspx.cs" Inherits="MetricTrac.SaveFilter" MasterPageFile="~/MasterPage.master"%>
<%@ Register src="../Control/OrglocationMultipick.ascx" tagname="OrgLocationSelect" tagprefix="mts" %>
<%@ Register src="../Control/GCASelect.ascx" tagname="GCASelect" tagprefix="mts" %>
<%@ Register src="~/Control/MultiSelectList.ascx" tagname="MultiSelectList" tagprefix="uc" %>
<asp:Content ID="cntFormJunc" ContentPlaceHolderID="PageBody" runat="server">
<div id="Div1" runat="server">
<telerik:RadAjaxPanel runat="server" ID="rapFrequency" LoadingPanelID="RadAjaxLoadingPanel1" EnableEmbeddedScripts="true" EnableAJAX="true" >
    
        <script type="text/javascript">
            function CloseOnReload(SaveArgument) {
                var w = GetRadWindow();
                w.argument = SaveArgument != '' ? SaveArgument : null;                
                w.close();
            }
        </script>        
        
        <mt:MTDetailsView runat="server" ObjectName="Metric Filter" ID="mfSaveFilter" DefaultMode="Insert"
            AutoGenerateInsertButton="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True"
            ShowCloseButtonSeparate="False" DataKeyNames="MetricFilterID" AutoGenerateRows="false" DataSourceID="dsMetricFilter" 
            OnAction="mfSaveFilter_Action" OnItemUpdated="mfSaveFilter_ItemUpdated" OnItemDeleted="mfSaveFilter_ItemDeleted"
            OnPreRender="mfSaveFilter_PreRender">
            <Fields>
                <mits:TextBoxField HeaderText="Name" DataField="Name" />
                <mits:TemplateField HeaderText="Org Locations">
                    <ItemTemplate>                        
                        <mts:OrgLocationSelect ID="orgLocationSelect1" runat="server" Width="300px" AutoPostBack="true" />
                    </ItemTemplate>
                </mits:TemplateField>
                <mits:TemplateField HeaderText="Group Category Aspect">
                    <ItemTemplate>
                        <mts:GCASelect ID="cASelect" runat="server" Width="300px" AutoPostBack="true" GCAID='<%#Bind("GroupCategoryAspectID")%>' />
                    </ItemTemplate>
                </mits:TemplateField>
                <mits:TemplateField HeaderText="Performance Indicators">
                    <ItemTemplate>
                        <uc:MultiSelectList ID="multiPI" runat="server" EntitiesName="Performance Indicators" OnClientSelectedIndexChanged="MetricSelectAjax" Width="300" AutoPostBack="true" ToolTip="Use &lt;Ctrl&gt;/&lt;Shift&gt; to select several Performance Indicators" />
                    </ItemTemplate>
                </mits:TemplateField>
                <mits:TemplateField HeaderText="Metrics">
                    <ItemTemplate>
                        <uc:MultiSelectList ID="multiMetric" runat="server" Width="300" EntitiesName="Metrics" AutoPostBack="False" ToolTip="Use &lt;Ctrl&gt;/&lt;Shift&gt; to select several Metrics"/>
                    </ItemTemplate>
                </mits:TemplateField>
                <mt:MTDropDownListField DataField="DataCollectorID" HeaderText="Collector" DataTextField="FullName" DataValueField="UserID" DataSourceId="dsUser" AddEmptyItem="true" AutoPostBack="true" />
            </Fields>
        </mt:MTDetailsView>
    
    
    <bll:BllDataSource runat="server" ID="dsMetricFilter" TableName="MetricFilter" 
        EnableAllChange="True" oninserted="dsMetricFilter_Inserted" />
    <bll:BllDataSource runat="server" ID="dsUser" TableName="Mc_User" BllSelectMethod="List"/>    
    <telerik:RadAjaxLoadingPanel runat="server" ID="RadAjaxLoadingPanel1" Wrap="true" Transparency="33" BackColor="LightGray" ><table style="height:100%; width:100%">
            <tr><td valign="top" align="center"><img alt="Loading ..." src="../images/loading6.gif" /></td></tr>
    </table></telerik:RadAjaxLoadingPanel>
</telerik:RadAjaxPanel>
</div>
</asp:Content>