//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetricTrac {
    
    
    public partial class ScoreCardDashboardEdit {
        
        /// <summary>
        /// mfScoreCardDashboard control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MetricTrac.MTControls.MTDetailsView mfScoreCardDashboard;
        
        /// <summary>
        /// dsScoreCardDashboard control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MetricTrac.Bll.Web.UI.WebControls.BllDataSource dsScoreCardDashboard;
        
        /// <summary>
        /// dsScoreCard control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MetricTrac.Bll.Web.UI.WebControls.BllDataSource dsScoreCard;
        
        /// <summary>
        /// dsScoreCardPeriod control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MetricTrac.Bll.Web.UI.WebControls.BllDataSource dsScoreCardPeriod;
    }
}
