<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="OrgMetricList.aspx.cs" Inherits="MetricTrac.OrgMetricList" MasterPageFile="~/MasterPage.master"%>
<asp:Content ID="cntOrgMetricList" ContentPlaceHolderID="PageBody" runat="server">
    <mt:MTGridView runat="server" ID="cgvMetric" DataKeyNames="MetricID"
        DataSourceID="ldsMetric" Width="99%" ColorScheme="Gray" AutoGenerateColumns="False"
        AutoGenerateEditButton="False" AutoGenerateDeleteButton="False" ShowAddLink="False"
        OnRowDataBound="cgvMetric_RowDataBound">
        <Columns>            
            <mits:TextField DataField="Name" HeaderText="Metric" SortExpression="Name" />
            <mits:TemplateField HeaderText="Org Locations">
                <ItemTemplate><table>
                    <asp:Repeater runat="server" ID="rpLocation"><ItemTemplate>
                        <tr><td><%#Eval("Name")%><%#((bool)Eval("IsVirtual")) ? " (related input)" : ""%></td></tr>
                    </ItemTemplate></asp:Repeater>
                </table></ItemTemplate>
            </mits:TemplateField>
        </Columns>
    </mt:MTGridView>
    <asp:LinqDataSource runat="server" ID="ldsMetric" 
        ContextTypeName="MetricTrac.Bll.LinqMicajahDataContext" TableName="Metric" 
        EnableDelete="false" OnSelecting="ldsMetric_Selecting"  />
</asp:Content>