<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="PerformanceIndicatorEdit.aspx.cs" Inherits="MetricTrac.PerformanceIndicatorEdit" MasterPageFile="~/MasterPage.master"%>
<%@ Register Src="~/Control/GCASelect.ascx" TagName="GCASelect" TagPrefix="c" %>
<%@ Register Src="~/Control/MetricList.ascx" TagName="MetricList" TagPrefix="c" %>
<%@ Register Namespace="MetricTrac.MTControls" TagPrefix="mt" Assembly="MetricTrac.Web"%>
<asp:Content ID="cntGCA" ContentPlaceHolderID="PageBody" runat="server">

    <div runat="server">
        <telerik:RadWindow runat="server" ID="rwEditValue" Modal="true" VisibleStatusbar="false" Height="525px" Width="790px" DestroyOnClose="false"            
            OnClientClose="clientCloseMetricAdd"/>
        <script type="text/javascript">
        	function GetHfFormulaParameters() {
        		return document.getElementById("<%=hfFormulaParameters.ClientID%>");
        	}
        	function GetHeExpression() {
        		return document.getElementById('<%=mfPerformanceIndicator.FindControl("heExpression").ClientID%>' + "_txt");
        	}
        	function OpenDialogWindow(url) {
        	    var oWnd = $find("<%=rwEditValue.ClientID%>");        	    
            	oWnd.setUrl(url);
                oWnd.Center();
                oWnd.show();
            }

            function clientCloseMetricAdd(sender, args) {
            	if (sender.argument == "Save") {
            		var rapMetric = $find("<%=rapMetric.ClientID%>");
            		rapMetric.ajaxRequest();
            	} else {
            		var arg = args.get_argument();
            		if(arg==null || arg==undefined || arg=="") return;
            		arg=arg.split("&");
            		if (arg.length != 4) return;
            		var heExpression = GetHeExpression();
            		heExpression.value = decodeURIComponent(arg[0]);
            		var hfFormulaParameters = GetHfFormulaParameters();
            		hfFormulaParameters.value = arg[1] + "&" + arg[2] + "&" + arg[3];
            	}
			}
			function OpenEditFormula(PIID) {
				var hfFormulaParameters = GetHfFormulaParameters();
				var params = "";//"&fp=" + encodeURIComponent(hfFormulaParameters.value);
				var heExpression = GetHeExpression();
				params = params + "&txt=" + encodeURIComponent(heExpression.value);				
				
				document.cookie = "FormulaParameters=" + escape(hfFormulaParameters.value);				
				OpenDialogWindow("PerformanceIndicatorFormulaEdit.aspx?PIID=" + PIID + params);
			}
        </script>
        <asp:HiddenField runat="server" ID="hfFormulaParameters" />
    </div>
    <table><tr><td>
    <mits:MagicForm ObjectName="Performance Indicator" ID="mfPerformanceIndicator" DataSourceID="odsPI"
        runat="server" AutoGenerateInsertButton="True"
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DefaultMode="Insert"
        ShowCloseButtonSeparate="False" DataKeyNames="PerformanceIndicatorID" AutoGenerateRows="false"
        RepeatColumns="1" OnAction="mfPerformanceIndicator_Action">
        <Fields>
            <mits:TextBoxField HeaderText="Name" DataField="Name" Columns="70" MaxLength="50" Required="true" />
            <mits:TextBoxField HeaderText="Alias" DataField="Alias" Columns="70" MaxLength="50" Required="false" />
            <mits:TextBoxField HeaderText="Code" DataField="Code" Columns="70" MaxLength="25" Required="false" />                                
            <mits:TemplateField>
                <EditItemTemplate>
                    <c:GCASelect runat="server" ID="sGroup" Width="380px" GCAID='<%#Bind("GroupCategoryAspectID")%>'/>
                </EditItemTemplate>
                <HeaderTemplate>GCA</HeaderTemplate>
            </mits:TemplateField>
            <mits:TemplateField HeaderText="Frequency">
                <EditItemTemplate>
                    <asp:DropDownList ID="ddlInputPeriod" runat="server" Width="380px"
                        DataSourceID="ldsFrequency" DataTextField="Name" DataValueField="FrequencyID" AppendDataBoundItems="true" SelectedValue='<%#Bind("FrequencyID") %>'>
                    </asp:DropDownList>
                </EditItemTemplate>
            </mits:TemplateField>
            <mits:TemplateField>
                <EditItemTemplate>
                    <asp:DropDownList ID="ddlSector" runat="server" Width="380px"
                        DataSourceID="ldsSector" DataTextField="Name" DataValueField="SectorID" AppendDataBoundItems="true" SelectedValue='<%#Bind("SectorID") %>'>
                        <asp:ListItem Text="" Value=""></asp:ListItem>
                    </asp:DropDownList>
                </EditItemTemplate>
                <HeaderTemplate>Sector</HeaderTemplate>
            </mits:TemplateField>
            <mits:TemplateField>
                <EditItemTemplate>
                    <asp:DropDownList ID="ddlRequirement" runat="server" Width="380px"
                        DataSourceID="ldsRequirement" DataTextField="Name" DataValueField="RequirementID" AppendDataBoundItems="true" SelectedValue='<%#Bind("RequirementID") %>'>
                        <asp:ListItem Text="" Value=""></asp:ListItem>
                    </asp:DropDownList>
                </EditItemTemplate>
                <HeaderTemplate>Requirement</HeaderTemplate>
            </mits:TemplateField>
            <mits:TemplateField>
                <EditItemTemplate>
                    <table cellpadding="0" cellspacing="0" border="0" style="margin-left:-5px;"><tr>
						<td><mits:TextBox ID="heExpression" runat="server" Text='<%#Bind("Formula")%>' Columns="57" Rows="5" TextMode="MultiLine" ReadOnly="true" /></td>
						<td>&nbsp;&nbsp;&nbsp;</td>
						<td><a onclick="OpenEditFormula('<%#Eval("PerformanceIndicatorID")%>'); return false;" href="PerformanceIndicatorFormulaEdit.aspx">Edit Formula</a></td>
					</tr></table>
                </EditItemTemplate>
                <HeaderTemplate>Formula</HeaderTemplate>
            </mits:TemplateField>
            <mits:TemplateField>
                <EditItemTemplate>
                    <asp:DropDownList ID="ddlUnitOfMeasure" runat="server" Width="305px"
                        DataSourceID="ldsUnitOfMeasure" DataTextField="SingularFullName" 
                        DataValueField="MeasureUnitId" AppendDataBoundItems="true" 
                        SelectedValue='<%#Bind("UnitOfMeasureID") %>'>
                        <asp:ListItem Text="" Value=""></asp:ListItem>
                    </asp:DropDownList>
                </EditItemTemplate>
                <HeaderTemplate>Output Unit of Measure</HeaderTemplate>
            </mits:TemplateField>
            <mits:TemplateField>
                <EditItemTemplate>
                    <asp:DropDownList ID="ddlAltUnitOfMeasure" runat="server" Width="305px"
                        DataSourceID="ldsUnitOfMeasure" DataTextField="SingularFullName" 
                        DataValueField="MeasureUnitId" AppendDataBoundItems="true" 
                        SelectedValue='<%#Bind("AltUnitOfMeasureID") %>'>
                        <asp:ListItem Text="" Value=""></asp:ListItem>
                    </asp:DropDownList>
                </EditItemTemplate>
                <HeaderTemplate>Alternative Unit of Measure</HeaderTemplate>
            </mits:TemplateField>
            <mits:TextBoxField HeaderText="Decimal Places" DataField="DecimalPlaces" Columns="5" MaxLength="5" Required="false" />
            <mt:MTHtmlEditorField HeaderText="Description" DataField="Description" ToolsFile="~/includes/ToolsFiles/BasicTools.xml" ControlStyle-Height="210px" />            
            <mt:MTHtmlEditorField HeaderText="Help Text" DataField="Help" ToolsFile="~/includes/ToolsFiles/BasicTools.xml" ControlStyle-Height="210px" />
        </Fields>
    </mits:MagicForm>
    
    <br />
    <div runat="server">
        <telerik:RadAjaxPanel runat="server" ID="rapMetric" EnableEmbeddedScripts="true" EnableAJAX="true">
            <table cellpadding="0" cellspacing="3">
                <tr>
                    <td><span class="Mf_Cpt">Metrics</span></td>
                    <td runat="server" align="right"><a class="Cgv_AddNew" href="javascript:OpenDialogWindow('MetricList.aspx?PerformanceIndicatorID=<%=PerformanceIndicatorID%>')">Add New Metric</a></td>
                </tr>
                <tr><td colspan="2">
                    <c:MetricList ID="cMetricList" runat="server" Mode="PIEdit" /></td></tr>
                <tr><td>&nbsp;</td></tr>
                <tr><td><span class="Mf_Cpt">Related Input Metrics</span></td></tr>
                <tr><td colspan="2">
                    <c:MetricList ID="RelatedMetric" runat="server" Mode="PiRef" />
                </td></tr>
            </table>            
        </telerik:RadAjaxPanel>
    </div>
    </td><td valign=top>
        <mits:EntityTreeView runat="server" ID="OrgTree" CheckBoxes="True" EntityId="4cda22f3-4f01-4768-8608-938dc6a06825" AllowRootNodeSelection="false"  />
    </td></tr></table>
     
    <asp:LinqDataSource runat="server" ID="ldsFrequency" ContextTypeName="MetricTrac.Bll.LinqMicajahDataContext" TableName="Frequency" />
    <asp:ObjectDataSource runat="server" ID="odsPI" DataObjectTypeName="MetricTrac.Bll.PerformanceIndicator+Extend, MetricTrac.Bll, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" TypeName="MetricTrac.PerformanceIndicatorEdit" SelectMethod="SelectPI" InsertMethod="SavePI" UpdateMethod="SavePI" DeleteMethod="DeletePI" />
    <asp:LinqDataSource runat="server" ID="ldsSector" ContextTypeName="MetricTrac.Bll.LinqMicajahDataContext" TableName="Sector"/>
    <asp:LinqDataSource runat="server" ID="ldsRequirement" ContextTypeName="MetricTrac.Bll.LinqMicajahDataContext" TableName="Requirement"/>
    <asp:LinqDataSource runat="server" ID="ldsUnitOfMeasure" ContextTypeName="MetricTrac.Bll.LinqMicajahDataContext" TableName="Mc_UnitsOfMeasure" onselecting="ldsUnitOfMeasure_Selecting"/>
</asp:Content>
