<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="DataCollectOutPutRule.aspx.cs" Inherits="MetricTrac.DataCollectOutPutRule" MasterPageFile="~/MasterPage.master"%>
<asp:Content ID="DataCollectorEdit" ContentPlaceHolderID="PageBody" runat="server">
    <mits:MagicForm runat="server" ObjectName="Data Collector Rule Output Param" ID="mfDataCollector" DefaultMode="Insert"
            AutoGenerateInsertButton="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True"
            ShowCloseButtonSeparate="False" DataKeyNames="RuleID" AutoGenerateRows="false" DataSourceID="ldsDataCollectorRuleOut" 
            OnAction="mfDataCollector_Action" OnItemUpdated="mfDataCollector_ItemUpdated" OnItemInserted="mfMDataCollector_ItemInserted" OnItemDeleted="mfDataCollector_ItemDeleted">
            <Fields>
                <mt:MTDropDownListField DataField="UserId" HeaderText="Data Collector" DataTextField="FullName" DataValueField="UserId" DataSourceId="dsUser" Width="300" />
            </Fields>
        </mits:MagicForm>
        
        <asp:LinqDataSource runat="server" ID="ldsDataCollectorRuleOut"
            ContextTypeName="MetricTrac.Bll.LinqMicajahDataContext" TableName="DataCollectorRuleOut"
            AutoGenerateWhereClause="true" EnableInsert="true" EnableDelete="true" EnableUpdate="true"
            OnSelecting="ldsDataCollectorRuleOut_Selecting">
        </asp:LinqDataSource>
        <bll:BllDataSource runat="server" ID="dsUser" TableName="Mc_User" BllSelectMethod="List"/>
</asp:Content>